DROP TABLE IF EXISTS Film_likes;
DROP TABLE IF EXISTS Friends;
DROP TABLE IF EXISTS Film_genre;
DROP TABLE IF EXISTS Films;
DROP TABLE IF EXISTS Genres;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Mpa;

CREATE TABLE Users (
  user_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR NOT NULL,
  login VARCHAR NOT NULL,
  name VARCHAR NULL,
  birthday DATE NOT NULL
);

CREATE TABLE Mpa (
  mpa_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR NOT NULL
);

CREATE TABLE Films (
  film_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  release_date DATE NOT NULL,
  duration INTEGER NOT NULL,
  mpa_id INTEGER NOT NULL,
  CONSTRAINT fk_films_mpa FOREIGN KEY (mpa_id) REFERENCES Mpa(mpa_id)
);

CREATE TABLE Genres (
  genre_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR NOT NULL
);

CREATE TABLE Film_genre (
  film_id INTEGER NOT NULL,
  genre_id INTEGER NOT NULL,
  PRIMARY KEY (film_id, genre_id),
  CONSTRAINT fk_fg_film FOREIGN KEY (film_id) REFERENCES Films(film_id) ON DELETE CASCADE,
  CONSTRAINT fk_fg_genre FOREIGN KEY (genre_id) REFERENCES Genres(genre_id) ON DELETE CASCADE
);

CREATE TABLE Friends (
  user_id INTEGER NOT NULL,
  friend_id INTEGER NOT NULL,
  status BOOLEAN NOT NULL,
  PRIMARY KEY (user_id, friend_id),
  CONSTRAINT fk_friends_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_friends_friend FOREIGN KEY (friend_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

CREATE TABLE Film_likes (
  film_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  PRIMARY KEY (film_id, user_id),
  CONSTRAINT fk_likes_film FOREIGN KEY (film_id) REFERENCES Films(film_id) ON DELETE CASCADE,
  CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);